language: node_js
node_js:
  - 7.9.0
install: yarn
addons:
  code_climate:
    repo_token: f3a8ee66a8f014150a18e38296c4999f3c81ad87f28f90ac8e223726a883a0e1
cache:
  directories:
    - node_modules
script:
  - yarn coverage
after_script:
  - ls -l 
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info